import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';

export interface WeatherPeriod {
  name: string;
  temperature: number;
  temperatureUnit: string;
  windSpeed: string;
  windDirection: string;
  shortForecast: string;
  detailedForecast: string;
  isDaytime: boolean;
  icon: string;
}

export interface WeatherAlert {
  id: string;
  event: string;
  headline: string;
  description: string;
  severity: string;
  urgency: string;
  onset: string;
  expires: string;
}

export interface WeatherPDFData {
  locationName: string;
  latitude: string;
  longitude: string;
  weatherPoint: {
    gridId: string;
    gridX: number;
    gridY: number;
  } | null;
  forecast: WeatherPeriod[];
  alerts: WeatherAlert[];
  generatedAt: string;
}

function wrapText(text: string, font: any, fontSize: number, maxWidth: number): string[] {
  const words = text.split(' ');
  const lines: string[] = [];
  let currentLine = '';

  for (const word of words) {
    const testLine = currentLine ? `${currentLine} ${word}` : word;
    if (font.widthOfTextAtSize(testLine, fontSize) > maxWidth && currentLine) {
      lines.push(currentLine);
      currentLine = word;
    } else {
      currentLine = testLine;
    }
  }
  if (currentLine) lines.push(currentLine);
  return lines;
}

const NAVY = rgb(0.10, 0.20, 0.40);
const NAVY_LIGHT = rgb(0.93, 0.95, 0.98);
const ALERT_RED = rgb(0.75, 0.08, 0.08);
const GREY = rgb(0.4, 0.4, 0.4);
const DARK = rgb(0.15, 0.15, 0.15);

export async function generateWeatherPDF(data: WeatherPDFData): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const PW = 612;
  const PH = 792;
  const MARGIN = 50;
  const CW = PW - 2 * MARGIN;
  const HEADER_H = 72;
  const FOOTER_H = 30;
  const BOTTOM = MARGIN + FOOTER_H;

  let page = pdfDoc.addPage([PW, PH]);
  let y = PH - HEADER_H - 16;

  const drawHeader = (isFirst: boolean) => {
    page.drawRectangle({ x: 0, y: PH - HEADER_H, width: PW, height: HEADER_H, color: NAVY });
    page.drawText('WEATHER FORECAST REPORT', {
      x: MARGIN, y: PH - 38, size: 18, font: boldFont, color: rgb(1, 1, 1),
    });
    const sub = isFirst ? 'National Weather Service — Operational Period Forecast' : '(continued)';
    page.drawText(sub, { x: MARGIN, y: PH - 58, size: 9, font, color: rgb(0.75, 0.82, 0.95) });
  };

  const drawFooter = () => {
    const pageCount = pdfDoc.getPageCount();
    const label = `Page ${pageCount} of ??`;
    page.drawLine({ start: { x: MARGIN, y: FOOTER_H + 8 }, end: { x: PW - MARGIN, y: FOOTER_H + 8 }, thickness: 0.5, color: GREY });
    page.drawText('Generated by OpPeriod', { x: MARGIN, y: FOOTER_H - 4, size: 7, font, color: GREY });
    page.drawText(label, { x: PW - MARGIN - 60, y: FOOTER_H - 4, size: 7, font, color: GREY });
  };

  const newPage = () => {
    drawFooter();
    page = pdfDoc.addPage([PW, PH]);
    drawHeader(false);
    y = PH - HEADER_H - 20;
  };

  const ensureSpace = (needed: number) => {
    if (y - needed < BOTTOM) newPage();
  };

  drawHeader(true);

  // Metadata block
  const locationText = data.locationName || `${data.latitude}, ${data.longitude}`;
  page.drawText(`Location: ${locationText}`, { x: MARGIN, y, size: 11, font: boldFont, color: DARK });
  y -= 16;
  if (data.weatherPoint) {
    page.drawText(
      `NWS Office: ${data.weatherPoint.gridId}  |  Grid: ${data.weatherPoint.gridX}, ${data.weatherPoint.gridY}`,
      { x: MARGIN, y, size: 9, font, color: GREY },
    );
    y -= 14;
  }
  page.drawText(`Generated: ${data.generatedAt}`, { x: MARGIN, y, size: 9, font, color: GREY });
  y -= 24;

  // Divider
  page.drawLine({ start: { x: MARGIN, y }, end: { x: PW - MARGIN, y }, thickness: 0.5, color: GREY });
  y -= 14;

  // Alerts section
  if (data.alerts.length > 0) {
    ensureSpace(36);
    page.drawRectangle({ x: MARGIN, y: y - 4, width: CW, height: 22, color: ALERT_RED });
    page.drawText('ACTIVE WEATHER ALERTS', {
      x: MARGIN + 10, y: y + 3, size: 11, font: boldFont, color: rgb(1, 1, 1),
    });
    y -= 30;

    for (const alert of data.alerts.slice(0, 5)) {
      ensureSpace(52);
      page.drawText(`▶  ${alert.event}  —  ${alert.severity}`, {
        x: MARGIN + 8, y, size: 10, font: boldFont, color: ALERT_RED,
      });
      y -= 14;
      const lines = wrapText(alert.headline || '', font, 9, CW - 16);
      for (const line of lines.slice(0, 2)) {
        ensureSpace(13);
        page.drawText(line, { x: MARGIN + 12, y, size: 9, font, color: DARK });
        y -= 12;
      }
      page.drawText(`Expires: ${new Date(alert.expires).toLocaleString()}`, {
        x: MARGIN + 12, y, size: 8, font, color: GREY,
      });
      y -= 18;
    }
    y -= 8;
    page.drawLine({ start: { x: MARGIN, y }, end: { x: PW - MARGIN, y }, thickness: 0.5, color: GREY });
    y -= 14;
  }

  // Extended forecast
  ensureSpace(36);
  page.drawRectangle({ x: MARGIN, y: y - 4, width: CW, height: 22, color: NAVY });
  page.drawText('EXTENDED FORECAST', {
    x: MARGIN + 10, y: y + 3, size: 11, font: boldFont, color: rgb(1, 1, 1),
  });
  y -= 30;

  for (const period of data.forecast.slice(0, 14)) {
    ensureSpace(62);

    // Period header row
    page.drawRectangle({ x: MARGIN, y: y - 3, width: CW, height: 20, color: NAVY_LIGHT });
    page.drawText(period.name, { x: MARGIN + 8, y: y + 3, size: 10, font: boldFont, color: NAVY });
    page.drawText(
      `${period.temperature}°${period.temperatureUnit}   |   Wind: ${period.windSpeed} ${period.windDirection}`,
      { x: MARGIN + 170, y: y + 3, size: 10, font, color: DARK },
    );
    y -= 22;

    const forecastLines = wrapText(period.detailedForecast, font, 9, CW - 16);
    for (const line of forecastLines.slice(0, 3)) {
      ensureSpace(13);
      page.drawText(line, { x: MARGIN + 8, y, size: 9, font, color: DARK });
      y -= 12;
    }
    y -= 8;
  }

  // Patch page-count placeholder in all footers now that we know total
  drawFooter();
  const totalPages = pdfDoc.getPageCount();
  const pages = pdfDoc.getPages();
  for (let i = 0; i < pages.length; i++) {
    const p = pages[i];
    p.drawRectangle({ x: PW - MARGIN - 70, y: FOOTER_H - 9, width: 70, height: 12, color: rgb(1, 1, 1) });
    p.drawText(`Page ${i + 1} of ${totalPages}`, {
      x: PW - MARGIN - 60, y: FOOTER_H - 4, size: 7, font, color: GREY,
    });
  }

  return await pdfDoc.save();
}
